package UserUtilities

const MAX_USERNAME_LENGTH = 20
const MIN_USERNAME_LENGTH = 3

const MAX_SECRET_QUESTION_LENGTH = 100
const MIN_SECRET_QUESTION_LENGTH = 0

const MAX_SECRET_ANSWER_LENGTH = 64
const MIN_SECRET_ANSWER_LENGTH = 0

const DEFAULT_USERNAME_LENGTH = 12

const DEFAULT_RATING = 1700

const VALID_USERNAME_CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"

const (
	USER_POWER_GUEST       = 0
	USER_POWER_UNCONFIRMED = 1
	USER_POWER_CONFIRMED   = 2
	USER_POWER_GM          = 3
	USER_POWER_DEV         = 4
	USER_POWER_ADMIN       = 5
)
const (
	UI_THEME_LIGHT = 0
	UI_THEME_DARK  = 1
)

const (
	COMMUNICATOR_CONTENT_CONTACTS     = 0
	COMMUNICATOR_CONTENT_CHATS        = 1
	COMMUNICATOR_CONTENT_NOTIFICATONS = 2
	COMMUNICATOR_CONTENT_BLOCKS       = 3
)
