package DashboardHelpers

const (
	TOPIC_PAGE_REQUEST                      = "pageRequest"
	TOPIC_CHANGE_PAGE                       = "changePage"
	TOPIC_UPDATE_PAGE_APPEND                = "updatePageAppend"
	TOPIC_UPDATE_PAGE_REPLACE               = "updatePageReplace"
	TOPIC_RESPONSE_MESSAGE                  = "responseMessage"
	TOPIC_INTRODUCTION                      = "get_introduction"
	TOPIC_GET_STATUS                        = "get_service_status"
	TOPIC_IS_PROCESSING_LOOP_RUNNING        = "get_processing_loop_status"
	TOPIC_GET_METRICS                       = "get_metrics"
	TOPIC_START                             = "start"
	TOPIC_STOP                              = "stop"
	TOPIC_COMMAND                           = "command"
	TOPIC_START_PROCESSINGLOOP_SEQUENTIALLY = "start_processingloop_sequentially"
	TOPIC_START_PROCESSINGLOOP_CONCURRENTLY = "start_processingloop_concurrently"
	TOPIC_STOP_PROCESSINGLOOP               = "stop_processingloop"
	TOPIC_PROCESS_NEXT_MESSAGE              = "process_next_message"
	TOPIC_UNPROCESSED_MESSAGE_COUNT         = "unprocessed_messages_count"
	TOPIC_SYNC_REQUEST                      = "sync_request"
	TOPIC_ASYNC_MESSAGE                     = "async_message"
	TOPIC_COLLECT_GARBAGE                   = "collect_garbage"
	TOPIC_HEAP_USAGE                        = "heap_usage"
	TOPIC_GOROUTINE_COUNT                   = "goroutine_count"
)
