package DashboardHelpers

const (
	TOPIC_PAGE_REQUEST                                   = "pageRequest"
	TOPIC_CHANGE_PAGE                                    = "changePage"
	TOPIC_UPDATE_PAGE_MERGE                              = "updatePageMerge"
	TOPIC_UPDATE_PAGE_REPLACE                            = "updatePageReplace"
	TOPIC_RESPONSE_MESSAGE                               = "responseMessage"
	TOPIC_INTRODUCTION                                   = "get_introduction"
	TOPIC_GET_STATUS                                     = "get_status"
	TOPIC_IS_MESSAGE_HANDLING_LOOP_STARTED               = "is_message_handling_loop_started"
	TOPIC_GET_METRICS                                    = "get_metrics"
	TOPIC_START                                          = "start"
	TOPIC_STOP                                           = "stop"
	TOPIC_COMMAND                                        = "command"
	TOPIC_CLOSE_CHILD                                    = "close_child"
	TOPIC_START_MESSAGE_HANDLING_LOOP_SEQUENTIALLY_CHILD = "start_message_handling_loop_sequentially_child"
	TOPIC_START_MESSAGE_HANDLING_LOOP_CONCURRENTLY_CHILD = "start_message_handling_loop_concurrently_child"
	TOPIC_STOP_MESSAGE_HANDLING_LOOP_CHILD               = "stop_message_handling_loop_child"
	TOPIC_HANDLE_NEXT_MESSAGE_CHILD                      = "handle_next_message_child"
	TOPIC_MULTI_SYNC_REQUEST                             = "multi_sync_request"
	TOPIC_MULTI_ASYNC_MESSAGE                            = "multi_async_message"
	TOPIC_START_MESSAGE_HANDLING_LOOP_SEQUENTIALLY       = "start_message_handling_loop_sequentially"
	TOPIC_START_MESSAGE_HANDLING_LOOP_CONCURRENTLY       = "start_message_handling_loop_concurrently"
	TOPIC_STOP_MESSAGE_HANDLING_LOOP                     = "stop_message_handling_loop"
	TOPIC_HANDLE_NEXT_MESSAGE                            = "handle_next_message"
	TOPIC_UNHANDLED_MESSAGE_COUNT                        = "unhandled_message_count"
	TOPIC_SYNC_REQUEST                                   = "sync_request"
	TOPIC_ASYNC_MESSAGE                                  = "async_message"
	TOPIC_COLLECT_GARBAGE                                = "collect_garbage"
	TOPIC_HEAP_USAGE                                     = "heap_usage"
	TOPIC_GOROUTINE_COUNT                                = "goroutine_count"
	TOPIC_GET_SYSTEMGE_CONNECTION_CHILDREN               = "get_systemge_connection_children"
	TOPIC_SUDOKU                                         = "sudoku"
)
